Repository src-d/go-mysql-server, pull requests merged in 2018-10, with the labels that each got.

#394 Fix get/set from global table.
  sql/analyzer/resolve_columns.go
  sql/analyzer/resolve_columns_test.go
  sql/plan/set.go
Labels: bug

#395 If deferredColumns is an alias then resolve it.
  engine_test.go
  sql/analyzer/resolve_columns.go
Labels: bug

#421 Fix substring/2
  engine_test.go
  sql/parse/parse.go
Labels: bug

#436 Adds Proper Apache License 2.0
  _scripts/go-vitess/LICENSE
  _scripts/go-vitess/Makefile
  _scripts/go-vitess/README.md
Labels: documentation

#437 Register COALESCE function. Update docs. Add integration test to engine.
  README.md
  SUPPORTED.md
  engine_test.go
  sql/expression/function/registry.go
Labels: documentation, enhancement

#451 One pilosa holder
  sql/index/pilosa/driver.go
Labels: proposal

#452 Implement SHOW VARIABLES
  engine_test.go
  sql/parse/parse.go
  sql/parse/parse_test.go
  sql/parse/variables.go
  sql/plan/showvariables.go
  sql/plan/showvariables_test.go
  sql/session.go
Labels: enhancement

#457 For numberT cast to the sqltype.
  engine_test.go
  sql/expression/function/aggregation/avg_test.go
  sql/type.go
  sql/type_test.go
Labels: bug

#478 No holder!
  sql/index/pilosa/driver.go
  sql/index/pilosa/driver_test.go
  sql/index/pilosa/lookup.go
Labels: bug

#464 Show warnings - implementation
  engine_test.go
  sql/analyzer/rules.go
  sql/analyzer/warnings.go
  sql/parse/parse.go
  sql/parse/parse_test.go
  sql/parse/warnings.go
  sql/plan/showwarnings.go
  sql/plan/showwarnings_test.go
  sql/session.go
  sql/session_test.go
Labels: enhancement

#505 Implement DATABASE() function.
  engine.go
  engine_test.go
  sql/expression/function/database.go
Labels: feature request

#504 Implement information_schema.tables
  _example/main.go
  engine_test.go
  sql/information_schema.go
  sql/plan/showdatabases.go
Labels: feature request

#506 Implement sql_select_limit
  engine_test.go
  sql/parse/parse.go
  sql/session.go
  sql/session_test.go
Labels: feature request

#511 Add support for information_schema.columns
  engine_test.go
  sql/information_schema.go
Labels: feature request

#514 Do not pull vt/logutil/level.go
  _scripts/go-vitess/Makefile
Labels: bug
