Repository src-d/go-mysql-server, pull requests merged in 2019-05, with the labels that each got.

#701 sql/analyzer: alias projected columns wrapped in converts
  engine_test.go
  sql/analyzer/convert_dates.go
  sql/analyzer/convert_dates_test.go
  sql/analyzer/rules.go
Labels: bug

#706 sql/analyzer: refactor and fix bugs in qualify_columns rule
  engine_test.go
  sql/analyzer/resolve_columns.go
  sql/analyzer/resolve_columns_test.go
  sql/plan/sort.go
Labels: enhancement

#713 server: guard sessions access in mutex
  server/context.go
  server/handler.go
Labels: bug

#711 Make ARRAY_LENGTH working with JSON arrays
  engine_test.go
  sql/expression/function/arraylength.go
Labels: proposal

#721 sql/analyzer: convert_dates should not change column name
  sql/analyzer/convert_dates.go
  sql/analyzer/convert_dates_test.go
Labels: bug

#722 Make PROCESSLIST and KILL compatible with MySQL
  server/handler.go
  server/handler_test.go
  sql/plan/processlist.go
  sql/plan/processlist_test.go
  sql/processlist.go
  sql/processlist_test.go
Labels: bug

#723 Implement SUBSTRING_INDEX UDF
  engine_test.go
  sql/expression/function/registry.go
  sql/expression/function/substring.go
  sql/expression/function/substring_test.go
Labels: feature

#731 Make boolean expression compatible with MySQL
  engine_test.go
  sql/expression/boolean.go
  sql/expression/boolean_test.go
  sql/type.go
Labels: bug

#732 Upgrade vitess to v1.7.0
  engine_test.go
  go.mod
  go.sum
Labels: 3rd-party, bug, proposal
