Repository src-d/go-mysql-server, pull requests merged in 2019-04, with the labels that each got.

#643 Make count int64 function
  engine_test.go
  sql/analyzer/aggregations_test.go
  sql/expression/function/aggregation/count.go
  sql/expression/function/aggregation/count_test.go
  sql/plan/group_by_test.go
Labels: proposal

#640 Check projection aliases when assigned to index.
  engine_test.go
  go.mod
  go.sum
  sql/analyzer/assign_indexes.go
  sql/analyzer/assign_indexes_test.go
Labels: bug

#655 Close iterators
  sql/analyzer/pushdown.go
  sql/index/pilosa/driver.go
  sql/plan/cross_join.go
  sql/plan/exchange.go
  sql/plan/exchange_test.go
  sql/plan/innerjoin.go
  sql/plan/process.go
Labels: bug

#660 Add build, tag for oniguruma, remove for mysql_go_regex, update README
  README.md
  internal/regex/regex_go.go
  internal/regex/regex_oniguruma.go
  internal/regex/regex_test.go
Labels: enhancement

#649 Added MySQL SLEEP function
  README.md
  SUPPORTED.md
  engine_test.go
  sql/expression/function/registry.go
  sql/expression/function/sleep.go
  sql/expression/function/sleep_test.go
Labels: feature

#628 YEARWEEK UDF function
  README.md
  SUPPORTED.md
  engine_test.go
  sql/expression/function/registry.go
  sql/expression/function/time.go
  sql/expression/function/time_test.go
Labels: feature

#650 Added from_base64 and to_base64
  README.md
  SUPPORTED.md
  engine_test.go
  sql/expression/function/registry.go
  sql/expression/function/tobase64_frombase64.go
  sql/expression/function/tobase64_frombase64_test.go
Labels: feature

#673 server: correctly set binary charset on blob fields
  server/handler.go
  server/handler_test.go
Labels: bug

#685 Suggest similar table/column/indexes names on missing errors
  ARCHITECTURE.md
  internal/similartext/similartext.go
  internal/similartext/similartext_test.go
  sql/analyzer/resolve_columns.go
  sql/catalog.go
  sql/catalog_test.go
  sql/functionregistry.go
  sql/index.go
  sql/plan/drop_index.go
  sql/plan/show_create_table.go
Labels: feature

#681 Make mapping per partition
  sql/index/pilosa/driver.go
  sql/index/pilosa/index.go
  sql/index/pilosa/iterator.go
  sql/index/pilosa/lookup.go
  sql/index/pilosa/mapping.go
  sql/index/pilosa/mapping_test.go
Labels: bug

#690 sql/analyzer: only check aliases to qualify in the topmost project
  engine_test.go
  sql/analyzer/resolve_columns.go
Labels: bug

#692 Try to order by function
  engine_test.go
  sql/analyzer/resolve_orderby.go
Labels: bug
