Repository src-d/go-mysql-server, pull requests merged in 2019-06, with the labels that each got.

#720 sql: implement EXPLODE and generators
  engine_test.go
  server/handler.go
  sql/analyzer/resolve_generators.go
  sql/analyzer/resolve_generators_test.go
  sql/analyzer/rules.go
  sql/analyzer/validation_rules.go
  sql/analyzer/validation_rules_test.go
  sql/expression/function/explode.go
  sql/expression/function/registry.go
  sql/generator.go
  sql/generator_test.go
  sql/plan/generate.go
  sql/plan/generate_test.go
  sql/type.go
  sql/type_test.go
Labels: enhancement

#738 Upgrade vitess to v1.8.0
  go.mod
  go.sum
Labels: proposal

#739 sql/analyzer: back-propagate expression names after adding convert
  sql/analyzer/convert_dates.go
  sql/analyzer/convert_dates_test.go
Labels: bug

#745 Replace fork go-vitess by original vitess.
  _scripts/go-vitess/LICENSE
  _scripts/go-vitess/Makefile
  _scripts/go-vitess/README.md
  _scripts/go-vitess/doc.go
  auth/audit.go
  auth/auth.go
  auth/native.go
  auth/none.go
  go.mod
  go.sum
  log.go
  server/context.go
  server/handler.go
  server/handler_test.go
  server/server.go
  sql/analyzer/resolve_columns.go
  sql/expression/arithmetic.go
  sql/parse/parse.go
  sql/parse/util.go
  sql/plan/set.go
  sql/type.go
  sql/type_test.go
Labels: proposal

#748 Implement JSON_UNQUOTE
  README.md
  SUPPORTED.md
  engine_test.go
  sql/expression/function/json_unquote.go
  sql/expression/function/json_unquote_test.go
  sql/expression/function/registry.go
  sql/functionregistry.go
Labels: feature, proposal

#744 Add metrics (engine, analyzer, regex, pilosa) based on go-kit interface.
  README.md
  _example/main.go
  engine.go
  go.mod
  go.sum
  internal/regex/regex.go
  internal/regex/regex_go.go
  internal/regex/regex_oniguruma.go
  sql/analyzer/analyzer.go
  sql/analyzer/parallelize.go
  sql/index.go
  sql/index/pilosa/driver.go
Labels: proposal

#752 sql/analyzer: refactor pushdown rule
  sql/analyzer/pushdown.go
Labels: enhancement

#750 sql/analyzer: refactor resolve_natural_joins rule
  go.mod
  go.sum
  sql/analyzer/resolve_natural_joins.go
  sql/plan/exchange.go
Labels: enhancement

#753 sql: correctly handle nulls in SQL type conversion
  sql/type.go
  sql/type_test.go
Labels: bug

#757 function: correctly transform up explode nodes
  engine_test.go
  sql/expression/function/explode.go
Labels: bug

#768 sql: use custom boolean coercion logic in condition evaluation
  engine_test.go
  sql/core.go
  sql/plan/filter.go
  sql/type.go
Labels: bug
